### ISSUE TITLE
Definitions for non-classes cannot be generated

### ISSUE THREAD

**Issue by mvidner** [YorickPeterse/ruby-lint#193]
I have lots of code which implements the singleton pattern like this:
```rb
class FooClass
  def foo; end
  def bar; end
end
Foo = FooClass.new
```

I can generate definitions for FooClass just fine, with rake, or more explicitly with
```console
$ ruby -I lib -r ruby-lint -r ruby-lint/definition_generator -r ./mytest/fooinstance.rb \
  -e 'RubyLint::DefinitionGenerator.new("FooClass","/tmp",overwrite: true).generate'
```

But that will not help in analyzing code that uses `Foo.foo; Foo.bar`. (I tried to address that in #179 with explicit mapping of constants to files byt we decided not to go that way.)

So I try to generate a definition of Foo, hoping to arrive at something isomorphic to the [STDIN definition](https://github.com/YorickPeterse/ruby-lint/blob/ad0e087f4c06bfdaec80df1ccd0f553da41a4d0e/lib/ruby-lint/definitions/core/stdin.rb#L6), but it fails:
```console
$ ruby -I lib -r ruby-lint -r ruby-lint/definition_generator -r ./mytest/fooinstance.rb \
  -e 'RubyLint::DefinitionGenerator.new("Foo","/tmp",overwrite: true).generate'
/local/home-mvidner/svn/ruby-lint/lib/ruby-lint/inspector.rb:41:in `inspect_constants': undefined method `name' for #<FooClass:0x00000002735468> (NoMethodError)
        from /local/home-mvidner/svn/ruby-lint/lib/ruby-lint/definition_generator.rb:53:in `generate'
        from -e:1:in `<main>'
```

**Comment by mvidner** [comment]
BTW it would be reasonable to use the standard [singleton](http://ruby-doc.org/stdlib-2.1.0/libdoc/singleton/rdoc/Singleton.html) library. But this is a big pile of legacy code I have to deal with and I cannot insert `.instance` literally to every method call.
