### ISSUE TITLE
Stack evel too deep

### ISSUE THREAD

**Issue by mensfeld** [YorickPeterse/ruby-lint#196]
When I try to analize this file:

```
class Destroy
  class Destroy
  end

  class Quit
    def process
      ::Destroy
    end
  end
end
```
I get this exception:

/home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope': stack level too deep (SystemStackError)
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/gems/ruby-lint-2.3.0/lib/ruby-lint/definition/ruby_object.rb:689:in `top_scope'
	 ... 10903 levels...
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/bin/ruby-lint:23:in `load'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/bin/ruby-lint:23:in `<main>'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/bin/ruby_executable_hooks:15:in `eval'
	from /home/mencio/.rvm/gems/ruby-2.3.1@enjin/bin/ruby_executable_hooks:15:in `<main>'
[Enjin (master)]$ be ruby-lint ../Kabe/app/concepts/gateway/organizations/operations.rb

**Comment by mensfeld** [comment]
Any news on that one?

**Comment by YorickPeterse** [comment]
@mensfeld No. I'm not actively working on ruby-lint, so no work has/is being done to solve this problem.

**Comment by mensfeld** [comment]
@YorickPeterse ah what a bummer :(
